/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.
 
 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
 // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

 
 
 
public void limpiarDatos() {
  txtName.setText("");
  }

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:874263://REGISTRAR
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  boolean vacio = txtName.getText().equals("") || txtPass.getPassword().equals("");
  if(!vacio){
  Usuario user = new Usuario(txtName.getText(), txtPass.getPassword());  
  user.registrar();
  this.limpiarDatos();
}else{
label1.setText("Campos vacíos");
this.limpiarDatos();
}
} //_CODE_:button1:874263:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:332251: //INGRESAR
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
  boolean vacio = txtName.getText().equals("") || txtPass.getPassword().equals("");
  if(!vacio){
  Usuario user = new Usuario(txtName.getText(), txtPass.getPassword());  
  user.verificar();
  gm = new GameManager(user);
  println(user.getUltimoNivelAprobado());
  this.limpiarDatos();
}else{
label1.setText("Campos vacíos");
this.limpiarDatos();
}
} //_CODE_:button2:332251:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:txtName:576998:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:txtName:576998:

public void pass(GPassword source, GEvent event) { //_CODE_:txtPass:580178:
  println("password1 - GPassword >> GEvent." + event + " @ " + millis());
} //_CODE_:txtPass:580178:

public void imgButton1_click1(GImageButton source, GEvent event) { //_CODE_:imgButton1:746074:
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton1:746074:

public void imgButton2_click1(GImageButton source, GEvent event) { //_CODE_:imgButton2:824997:
  println("imgButton2 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton2:824997:

public void imgButton3_click1(GImageButton source, GEvent event) { //_CODE_:imgButton3:689104:
  println("imgButton3 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton3:689104:


//borrar GUI
public void borrarGUI(){
  button1.setVisible(false);
  button2.setVisible(false);
  txtName.setVisible(false);
  txtPass.setVisible(false);
  label1.setVisible(false);
  label2.setVisible(false);
  label3.setVisible(false);
  imgButton1.setVisible(false);
  imgButton2.setVisible(false);
  imgButton3.setVisible(false);
}

// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI() {
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.CYAN_SCHEME);
  G4P.setDisplayFont("Arial Black", G4P.BOLD, 14);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Login");
  button1 = new GButton(this, 570, 270, 100, 50);
  button1.setText("Registrarse");
  button1.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 570, 212, 100, 50);
  button2.setText("Ingresar");
  button2.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  button2.addEventHandler(this, "button2_click1");
  txtName = new GTextField(this, 545, 92, 160, 30, G4P.SCROLLBARS_NONE);
  txtName.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  txtName.setOpaque(true);
  txtName.addEventHandler(this, "textfield1_change1");
  txtPass = new GPassword(this, 545, 140, 160, 30);
  txtPass.setMaxWordLength(10);
  txtPass.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  txtPass.setOpaque(true);
  txtPass.addEventHandler(this, "pass");
  label1 = new GLabel(this, 545, 174, 159, 18);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setLocalColorScheme(GCScheme.RED_SCHEME);
  label1.setOpaque(false);
  label2 = new GLabel(this, 545, 69, 80, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Usuario");
  label2.setOpaque(false);
  label3 = new GLabel(this, 545, 121, 80, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Password");
  label3.setOpaque(false);
  imgButton1 = new GImageButton(this, 500, 93, 35, 25, new String[] { "usuario.png", "usuario.png", "usuario.png" } );
  imgButton1.addEventHandler(this, "imgButton1_click1");
  imgButton2 = new GImageButton(this, 500, 142, 35, 25, new String[] { "padlock.png", "padlock.png", "padlock.png" } );
  imgButton2.addEventHandler(this, "imgButton2_click1");
  imgButton3 = new GImageButton(this, 475, 11, 250, 50, new String[] { "logo.png", "logo.png", "logo.png" } );
  imgButton3.addEventHandler(this, "imgButton3_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GButton button2; 
GTextField txtName; 
GPassword txtPass; 
GLabel label1; 
GLabel label2; 
GLabel label3; 
GImageButton imgButton1; 
GImageButton imgButton2; 
GImageButton imgButton3; 
